// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoMhpr1L32CfOyfh_lONOkihv4uLk1Zos',
    appId: '1:101215459043:web:b92c371703e2021b0197d6',
    messagingSenderId: '101215459043',
    projectId: 'patapp-d9860',
    authDomain: 'patapp-d9860.firebaseapp.com',
    storageBucket: 'patapp-d9860.appspot.com',
    measurementId: 'G-VQH24SDNH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ1jRzXx4WXVH3jumfm87gEOC3GYpHoNE',
    appId: '1:101215459043:android:8f1b5682d3f070d10197d6',
    messagingSenderId: '101215459043',
    projectId: 'patapp-d9860',
    storageBucket: 'patapp-d9860.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVCbpamxB5pcjED15cn__WgarEf7550Vk',
    appId: '1:101215459043:ios:3a3654bf5cf454a10197d6',
    messagingSenderId: '101215459043',
    projectId: 'patapp-d9860',
    storageBucket: 'patapp-d9860.appspot.com',
    androidClientId: '101215459043-hu6o2infg15ejho5en8qgi9i7u8ltovl.apps.googleusercontent.com',
    iosBundleId: 'com.example.maestropat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVCbpamxB5pcjED15cn__WgarEf7550Vk',
    appId: '1:101215459043:ios:920640996cebcc760197d6',
    messagingSenderId: '101215459043',
    projectId: 'patapp-d9860',
    storageBucket: 'patapp-d9860.appspot.com',
    androidClientId: '101215459043-hu6o2infg15ejho5en8qgi9i7u8ltovl.apps.googleusercontent.com',
    iosBundleId: 'com.example.maestropat.RunnerTests',
  );
}
